variables:
  IMAGE_ORG: cokoapps
  IMAGE_NAME: ketida-server-develop
  WORKDIR: /home/node/server

stages:
  - build
  - lint

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA ./ -f Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

lint js:
  stage: lint
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR
    - yarn eslint .
