variables:
  IMAGE_ORG: cokoapps
  IMAGE_NAME_DEVELOP: ketida-server-develop
  IMAGE_NAME_PRODUCTION: ketida-server
  WORKDIR: /home/node/server

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - build
  - test
  - release

build:
  stage: build
  image: docker:23
  services:
    - docker:23-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA ./ -f Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA

lint:
  stage: test
  image: $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR
    - yarn eslint .
    - yarn prettier --check .

release:
  stage: release
  only:
    - main
  image: $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA
  script:
    - yarn semantic-release --dry-run
