variables:
  IMAGE_ORG: cokoapps
  IMAGE_NAME_DEVELOP: ketty-server-develop
  IMAGE_NAME_PRODUCTION: ketty-server
  WORKDIR: /home/node/server

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - build
  - test
  - release
  # - publish

build:
  stage: build
  image: docker:23
  services:
    - docker:23-dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker build --tag $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA ./ -f Dockerfile-development
    - docker push $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA

lint:
  stage: test
  image: $IMAGE_ORG/$IMAGE_NAME_DEVELOP:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR
    - yarn eslint .
    - yarn prettier --check .

release:
  stage: release
  only:
    - main
  image: node:20-bullseye
  before_script:
    - npm i -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/gitlab
  script:
    - semantic-release
# publish to dockerhub:
#   stage: publish
