version: '2'

services:
  server:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
      - ${WS_SERVER_PORT:-3333}:${WS_SERVER_PORT:-3333}
    environment:
      - NODE_ENV=production
      - SERVER_IDENTIFIER=${SERVER_IDENTIFIER}
      - KETIDA_FLAVOUR=${KETIDA_FLAVOUR}
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - SERVER_URL=${SERVER_URL}
      - WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_SERVE_CLIENT=false
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_GIVEN_NAME=${ADMIN_GIVEN_NAME}
      - ADMIN_SURNAME=${ADMIN_SURNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SERVER_PORT=${SERVER_PORT}
      - WS_SERVER_PORT=${WS_SERVER_PORT}
      - WS_HEARTBEAT_INTERVAL=${WS_HEARTBEAT_INTERVAL:-10000}
      - FAIL_SAFE_UNLOCKING_INTERVAL=${FAIL_SAFE_UNLOCKING_INTERVAL:-12000}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - PASSWORD_RESET_PATH_TO_PAGE=/password-reset
      - S3_PROTOCOL=${S3_PROTOCOL}
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID_USER=${S3_ACCESS_KEY_ID_USER}
      - S3_SECRET_ACCESS_KEY_USER=${S3_SECRET_ACCESS_KEY_USER}
      - S3_BUCKET=uploads
      - SERVICE_EPUB_CHECKER_CLIENT_ID=${SERVICE_EPUB_CHECKER_CLIENT_ID}
      - SERVICE_EPUB_CHECKER_SECRET=${SERVICE_EPUB_CHECKER_SECRET}
      - SERVICE_EPUB_CHECKER_URL=${SERVICE_EPUB_CHECKER_URL}
      - SERVICE_ICML_CLIENT_ID=${SERVICE_ICML_CLIENT_ID}
      - SERVICE_ICML_SECRET=${SERVICE_ICML_SECRET}
      - SERVICE_ICML_URL=${SERVICE_ICML_URL}
      - SERVICE_PAGEDJS_CLIENT_ID=${SERVICE_PAGEDJS_CLIENT_ID}
      - SERVICE_PAGEDJS_SECRET=${SERVICE_PAGEDJS_SECRET}
      - SERVICE_PAGEDJS_URL=${SERVICE_PAGEDJS_URL}
      - SERVICE_XSWEET_CLIENT_ID=${SERVICE_XSWEET_CLIENT_ID}
      - SERVICE_XSWEET_SECRET=${SERVICE_XSWEET_SECRET}
      - SERVICE_XSWEET_URL=${SERVICE_XSWEET_URL}
      - FEATURE_UPLOAD_DOCX_FILES=${FEATURE_UPLOAD_DOCX_FILES}
      - FEATURE_BOOK_STRUCTURE=${FEATURE_BOOK_STRUCTURE}
      - FEATURE_POD=${FEATURE_POD:-false}
      - AI_ENABLED=${AI_ENABLED:-false}
      - TEMP_DIRECTORY_CRON_JOB_SCHEDULE=${TEMP_DIRECTORY_CRON_JOB_SCHEDULE}
      - TEMP_DIRECTORY_CRON_JOB_OFFSET=${TEMP_DIRECTORY_CRON_JOB_OFFSET}
      - TEMP_DIRECTORY_CLEAN_UP=${TEMP_DIRECTORY_CLEAN_UP}
