FROM node:16.19.0-bullseye

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y ranger vim python netcat imagemagick potrace ghostscript

RUN sed -i.bak 's/rights="none" pattern="PS"/rights="read | write" pattern="PS"/g' /etc/ImageMagick-6/policy.xml
RUN sed -i.bak 's/rights="none" pattern="EPS"/rights="read | write" pattern="EPS"/g' /etc/ImageMagick-6/policy.xml


WORKDIR /home/node/server

COPY package.json .
COPY yarn.lock .

RUN chown -R node:node .
USER node


RUN yarn install
# RUN yarn cache clean
COPY --chown=node:node . .
