module.exports = {
  templates: [
    // {
    //   label: "atla",
    //   url: "https://gitlab.coko.foundation/ketty-templates/atla",
    //   assetsRoot: "dist",
    //   supportedNoteTypes: ["footnotes"],
    // },
    {
      label: 'lategrey',
      url: 'https://gitlab.coko.foundation/ketty-templates/lategrey',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Part-page',
    },
    {
      label: 'significa',
      url: 'https://gitlab.coko.foundation/ketty-templates/significa',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Part-page-css',
    },
    {
      label: 'bikini',
      url: 'https://gitlab.coko.foundation/ketty-templates/bikini',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Toc-with-part',
    },
    {
      label: 'vanilla',
      url: 'https://gitlab.coko.foundation/ketty-templates/vanilla',
      assetsRoot: 'dist',
      default: true,
      supportedNoteTypes: ['footnotes'],
      branch: 'Part-page',
    },
    {
      label: 'atosh',
      url: 'https://gitlab.coko.foundation/ketty-templates/atosh.git',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Toc-with-part',
    },
    {
      label: 'eclypse',
      url: 'https://gitlab.coko.foundation/ketty-templates/eclypse.git',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Toc-with-part',
    },
    {
      label: 'logical',
      url: 'https://gitlab.coko.foundation/ketty-templates/logical.git',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'toc-with-part',
    },
    {
      label: 'tenberg',
      url: 'https://gitlab.coko.foundation/ketty-templates/tenberg.git',
      assetsRoot: 'dist',
      supportedNoteTypes: ['footnotes'],
      branch: 'Toc-with-part',
    },
  ],
}
